---
- hosts: master

  vars:
    certGenDir: "{{ lookup('env','CERTS_GEN_DIR') }}"
    kubeconfigDir: "{{ lookup('env','KUBECONFIG_DIR') }}"

  tasks:
    - stat: path=/usr/local/bin/kubectl
      register: kubectl_exists

    - name: "Install Kubernetes Controller Binaries"
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.9.0/bin/linux/amd64/{{ item }}
        dest: /usr/local/bin/
        mode: "+x"
      become: true
      with_items:
        - "kubectl"
        - "kube-apiserver"
        - "kube-controller-manager"
        - "kube-scheduler"
      when: kubectl_exists.stat.exists == false

    - name: Create directories
      file: path={{ item }} state=directory
      with_items:
        - "/var/lib/kubernetes/"
      become: true

    - name: "Copy certificates and config to kubernetes dir"
      copy: src={{ item }} dest="/var/lib/kubernetes/"
      with_items:
        - "{{ certGenDir }}/ca.pem"
        - "{{ certGenDir }}/ca-key.pem"
        - "{{ certGenDir }}/kubernetes-key.pem"
        - "{{ certGenDir }}/kubernetes.pem"
        - "{{ kubeconfigDir }}/encryption-config.yaml"
      become: true

    - name: "Generate systemd service files"
      template:
        src: templates/{{ item }}.service.j2
        dest: /etc/systemd/system/{{ item }}.service
      with_items:
        - "kube-apiserver"
        - "kube-scheduler"
        - "kube-controller-manager"
      become: true

    - name: "Start systemd services"
      systemd:
        state: restarted
        daemon_reload: yes
        enabled: yes
        name: "{{ item }}"
      with_items:
        - "kube-apiserver"
        - "kube-scheduler"
        - "kube-controller-manager"
      become: true

    - name: Wait for services to start
      wait_for: timeout=20
      delegate_to: localhost
