---
- hosts: worker

  tasks:
    - name: configure static route
      shell: |
        route add -net 192.168.123.0/24 gw 192.168.10.23 dev enp0s8
        route add -net 192.168.124.0/24 gw 192.168.10.24 dev enp0s8
      become: true
      register: command_result
      failed_when: "not(command_result.rc == 0 or 'SIOCADDRT: File exists' in command_result.stderr)"