---
- hosts: worker

  vars:
    certGenDir: "{{ lookup('env','CERTS_GEN_DIR') }}"

  tasks:
    - name: "Copy certificates to workers"
      copy: src={{ item }} dest="~/certs/"
      with_items:
        - "{{ certGenDir }}/ca.pem"
        - "{{ certGenDir }}/{{ inventory_hostname }}.pem"
        - "{{ certGenDir }}/{{ inventory_hostname }}-key.pem"
        - "{{ certGenDir }}/kube-proxy.pem"

- hosts: master

  vars:
    certGenDir: "{{ lookup('env','CERTS_GEN_DIR') }}"

  tasks:
    - name: "Copy certificates to masters"
      copy: src={{ item }} dest="~/certs/"
      with_items:
        - "{{ certGenDir }}/ca.pem"
        - "{{ certGenDir }}/ca-key.pem"
#        - "{{ certGenDir }}/kubernetes-key.pem"
#        - "{{ certGenDir }}/kubernetes.pem"

