apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-ds
  namespace: ds
spec:
  selector:
    matchLabels:
      name: busybox-ds
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: busybox-ds
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sleep
        - "3600"
