apiVersion: v1
kind: Pod
metadata:
    name: vip
    labels:
      env: test
spec:
    containers:
        - name: busybox
          image: busybox
          args:
              - sleep
              - "360"
