apiVersion: v1
kind: Pod
metadata:
  name: configmapPod
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /config
      name: mapVolume
  volumes:
    - name: mapVolume
      configMap:
        name: map
