apiVersion: v1
kind: Pod
metadata:
  name: vol
  labels:
    app: vol
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /busy
      name: test
    imagePullPolicy: IfNotPresent
  - image: busybox
    name: box
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /box
      name: test
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  volumes:
  - name: test
    emptyDir: {}
