apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      subPath: mysql # sub-path inside the referenced volume instead of its root
  volumes:
  - name: cache-volume
    emptyDir: {}