# LimitRange sets resource usage limits for each kind of resource in a Namespace
# https://kubernetes.io/docs/tasks/administer-cluster/memory-default-namespace/
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/#limitrange-v1-core
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container