# https://kubernetes.io/docs/tasks/administer-cluster/quota-api-object/
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
#   API Objects quota
    persistentvolumeclaims: "1"
    services.loadbalancers: "2"
    services.nodeports: "0"
