kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    namespace: production
    name: dev-prod
rules:
    - apiGroups: ["", "extensions", "apps"]
      resources: ["deployments", "replicaSets", "pods"]
      verbs: ["get", "list", "watch"]

