apiVersion: v1
kind: Pod
metadata:
    name: mysql
    namespace: default
spec:
    containers:
        - name: mysql
          image: mysql:5.5
          env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                          secretKeyRef:
                                  name: mysql
                                  key: password
