apiVersion: v1
kind: Pod
metadata: 
    name: pod-with-secret
spec:
    containers:
    - name: redis
      image: redis
      volumeMounts:
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true
      - name: bar
        mountPath: "/etc/bar"
        readOnly: true
    volumes:
    - name: foo
      secret:
        secretName: db-user-pass
    - name: bar
      secret:
          secretName: manual-secret

