apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: developement
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["my-configmap"] # restrict the role to specifically named resource
  verbs: ["update", "get"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]